controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 30.0

    base_frame_id: base_link

    left_wheel_names: ['joint_left_wheel']
    right_wheel_names: ['joint_right_wheel']
    wheel_separation: 0.53
    wheel_radius: 0.0675

    use_stamped_vel: false