controller_manager:
  ros_parameters:
    update rate: 30
    use_sim_time: true

    diff cont:
      type: diff_drive_controller/DiffDriveController

    joint broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros_parameters:

    publish rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 3.14
    wheel_radius: 0.675

    use_stamped_vel: false